pReader/Poster/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.index,name='index'),
]

pReader/pReader/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('poem/',include('poem.urls')),
    path('admin/', admin.site.urls),
    path('Poster/',include('Poster.urls')),
]

pReader/poem/urls.py
from django.urls import path

from . import views
app_name='poem'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/detail/',views.detail,name='detail'),
    path('<int:question_id>/results/',views.results,name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
]

pReader/Poster/models.py
from django.db import models

# Create your models here.

pReader/poem/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text;

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text;
class User(models.Model):
    user_descript = models.CharField(max_length=200)
    user_name = models.CharField(max_length=10)
    user_name = models.IntegerField(default=0)

pReader/Poster/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def index(request):
    return HttpResponse("Hello,World");

pReader/poem/views.py
from django.shortcuts import render,get_object_or_404
from django.template import loader
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question
from django.urls import reverse
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('poems/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))
def detail(request, question_id):
    question=get_object_or_404(Question,pk=question_id);
    return render(request, 'poems/detail.html', {'question': question})
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'poems/results.html', {'question': question})
def vote(request, question_id):
    question=get_object_or_404(Question,pk=question_id);
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request,'poems/detail.html',{
            'question':question,
            'error_message':"You didn't select a choice.",
        })
    else:
        selected_choice.votes+=1;
        selected_choice.save();
    return  HttpResponseRedirect(reverse('poem:results',args=(question_id,)))

pReader/stroy/views.py
from django.shortcuts import render

# Create your views here.

pReader/Poster/templates/index/index.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
  <title>Bootstrap 101 Template</title>

  <!-- Bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
  <link type="text/css" rel="styleSheet" href="../../static/index/base.css" <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持
    HTML5 元素和媒体查询（media queries）功能 -->
  <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
  <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
</head>

<body>
  <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
          data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Brand</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#" class="active"> 主页</a></li>
          <li><a href="#"> 特点</a></li>
          <li><a href="#"> 关于</a></li>

          <!-- <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
              aria-expanded="false">关于 <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li> -->
          <li><a href="#"> 展示</a></li>
          <li><a href="#"> 团队</a></li>
          <li><a href="#"> 联系</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <section class="mainPage">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="../../images/screens.png" alt="...">
          <div class="carousel-caption">
            <h1>Hello World</h1>
            <p>Add captions to your slides easily with the .carousel-caption element within any .item. Place just about
              any optional HTML within there and it will be automatically aligned and formatted.</p>
          </div>
        </div>
        <div class="item">
          <img src="../../images/screens.png" alt="...">
          <div class="carousel-caption">
            <h1>Hello World</h1>
            <p>Add captions to your slides easily with the .carousel-caption element within any .item. Place just about
              any optional HTML within there and it will be automatically aligned and formatted.</p>
          </div>
        </div>
        <div class="item">
          <img src="../../images/screens.png" alt="...">
          <div class="carousel-caption">
            <h1>Hello World</h1>
            <p>Add captions to your slides easily with the .carousel-caption element within any .item. Place just about
              any optional HTML within there and it will be automatically aligned and formatted.</p>
            <p>
              <button type="button" class="btn btn-primary btn-lg">（大按钮）Large button</button>
              <button type="button" class="btn btn-default btn-lg">（大按钮）Large button</button>
            </p>
          </div>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </section>


  <section class="teamsPage">
    <div class="teams-title">
      <h1 class="text-center">我们的团队</h1>
    </div>
    <div class="row" id="tmTeams">
      <div class="col-lg-4">
        <div class="tm-bg-white-transparent tm-feature-box">
          <h3 class>多平台</h3>

          <div class="teams-icon-container">
                  <img  src="../..//images/responsive.svg">
          </div>

          <p class="text-center">Download and use this layout for your sites. Total 5 HTML pages included.</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="tm-bg-white-transparent tm-feature-box">
          <h3>个性化</h3>

          <div class="teams-icon-container">
              <img src="../..//images/customizable.svg">
          </div>

          <p class="text-center">Download and use this layout for your sites. Total 5 HTML pages included.</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="tm-bg-white-transparent tm-feature-box">
          <h3 class>流畅美观</h3>

          <div class="teams-icon-container">
              <img src="../../images/design.svg">
          </div>

          <p class="text-center">Download and use this layout for your sites. Total 5 HTML pages included.</p>
        </div>
      </div>

    </div>


  </section>
  <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
  <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
</body>

</html>

pReader/poem/templates/poems/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'poem:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

pReader/poem/templates/poems/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'poems/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'poem:detail' question.id%}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

pReader/poem/templates/poems/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'poem:detail' question.id %}">Vote again?</a>